### ISSUE TITLE
%install issues

### ISSUE THREAD

**Issue by kasicka** [theforeman/npm2rpm#7]
Files like CHANGELOG.md README.md and LICENSE don't belong to %install. Also for the sake of readability, multiple .js files could be replaced by *.js.

**Comment by dLobatog** [comment]
I tried to make it as close to npm as possible. When you install globally a module with npm (npm install -g) , those files are included in /usr/lib/node_modules/yourmodule . If you later on want to use `npm link` in your project, apparently everything needs to exist in the directory so that npm understands it.

I do agree about the *.js thing being annoying, to be fixed.

**Comment by ekohl** [comment]
This happens because of the unpacking phase when using bundled packages. They're not needed when using the single style.

**Comment by ekohl** [comment]
In https://github.com/dLobatog/npm2rpm/pull/36 I removed them from ```%install``` and use them in ```%files``` with ```%doc``` and ```%license```.

**Comment by ekohl** [comment]
Closing since #36 was merged.
